apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
resources:
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.7.2/manifests/install.yaml
- ns.yaml
secretGenerator:
- name: my-repo
  literals:
    - type=git
    - url=https://github.com/mmigout/formation
  options:
    labels:
      argocd.argoproj.io/secret-type: repository